package parsers

import python.{ Poetry, PoetryFiles }

import cats.Id
import cats.effect.IOApp
import cats.effect.IO

object ParsersMain extends IOApp.Simple:
  def run: IO[Unit] =
    val poetry = Poetry.make[IO]
    val pyProject = """[tool.poetry]
        |name = "data"
        |version = "0.1.0"
        |description = ""
        |authors = ["naylepsh <naylepsh@gmail.com>"]
        |readme = "README.md"
        |
        |[tool.poetry.dependencies]
        |python = "^3.11"
        |returns = "0.20.0"
        |
        |
        |[build-system]
        |requires = ["poetry-core"]
        |build-backend = "poetry.core.masonry.api"""".stripMargin
    val lock = """# This file is automatically @generated by Poetry 1.7.1 and should not be changed by hand.
        |
        |[[package]]
        |name = "returns"
        |version = "0.20.0"
        |description = "Make your functions return something meaningful, typed, and safe!"
        |optional = false
        |python-versions = ">=3.7,<4.0"
        |files = [
        |    {file = "returns-0.20.0-py3-none-any.whl", hash = "sha256:e743a692d4585efbe2bb33703b18c332754b2844ba2ee7e40dc5d22e3301f36f"},
        |    {file = "returns-0.20.0.tar.gz", hash = "sha256:90d21b03bbd9a6dc7d44317ca36e8080d2428679c74f2f15ec386816d09c4ece"},
        |]
        |
        |[package.dependencies]
        |typing-extensions = ">=4.0,<5.0"
        |
        |[[package]]
        |name = "typing-extensions"
        |version = "4.9.0"
        |description = "Backported and Experimental Type Hints for Python 3.8+"
        |optional = false
        |python-versions = ">=3.8"
        |files = [
        |    {file = "typing_extensions-4.9.0-py3-none-any.whl", hash = "sha256:af72aea155e91adfc61c3ae9e0e342dbc0cba726d6cba4b6c72c1f34e47291cd"},
        |    {file = "typing_extensions-4.9.0.tar.gz", hash = "sha256:23478f88c37f27d76ac8aee6c905017a143b0b1b886c3c9f66bc2fd94f9f5783"},
        |]
        |
        |[metadata]
        |lock-version = "2.0"
        |python-versions = "^3.11"
        |content-hash = "0b5b280fce119e317e2d4d66e08fe5f5bfa0041ec7cde34dbf25349a0a5d0cfa"""".stripMargin
    val files  = PoetryFiles(pyProject, lock)

    poetry
      .update("returns", "0.20.0", "0.21.0", files)
      .flatMap(IO.println)
